# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GraphViz-Traverse
version:      0.01
version_from: lib/GraphViz/Traverse.pm
installdirs:  site
requires:
    Carp:                          0
    File::Basename:                0
    File::Find:                    0
    GraphViz:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
